name: llm-env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.17=h5eee18b_0
  - pip=25.2=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.11.13=h1a3bd86_0
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py311h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.14=h993c535_1
  - wheel=0.45.1=py311h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.3.1
      - accelerate==1.9.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.14
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - attrs==25.3.0
      - bitsandbytes==0.46.1
      - calflops==0.3.2
      - certifi==2025.7.14
      - chardet==5.2.0
      - charset-normalizer==3.4.2
      - click==8.2.1
      - colorama==0.4.6
      - contourpy==1.3.3
      - cycler==0.12.1
      - dataproperty==1.1.0
      - datasets==4.0.0
      - dill==0.3.8
      - einops==0.8.1
      - evaluate==0.4.5
      - filelock==3.18.0
      - flash-attn==2.7.4.post1
      - fonttools==4.61.1
      - frozenlist==1.7.0
      - fsspec==2024.9.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - hf-xet==1.1.5
      - huggingface-hub==0.34.1
      - idna==3.10
      - jinja2==3.1.6
      - joblib==1.5.1
      - jsonargparse==4.40.1
      - jsonlines==4.0.0
      - kiwisolver==1.4.9
      - lm-eval==0.4.9.1
      - lxml==6.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.8
      - mbstrdecoder==1.1.4
      - more-itertools==10.7.0
      - mpmath==1.3.0
      - multidict==6.6.3
      - multiprocess==0.70.16
      - networkx==3.5
      - nltk==3.9.1
      - numexpr==2.11.0
      - numpy==2.3.2
      - nvidia-cublas-cu12==12.8.3.14
      - nvidia-cuda-cupti-cu12==12.8.57
      - nvidia-cuda-nvrtc-cu12==12.8.61
      - nvidia-cuda-runtime-cu12==12.8.57
      - nvidia-cudnn-cu12==9.7.1.26
      - nvidia-cufft-cu12==11.3.3.41
      - nvidia-cufile-cu12==1.13.0.11
      - nvidia-curand-cu12==10.3.9.55
      - nvidia-cusolver-cu12==11.7.2.55
      - nvidia-cusparse-cu12==12.5.7.53
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.8.61
      - nvidia-nvtx-cu12==12.8.55
      - packaging==25.0
      - pandas==2.3.1
      - pathvalidate==3.3.1
      - peft==0.16.0
      - pillow==11.0.0
      - platformdirs==4.3.8
      - portalocker==3.2.0
      - propcache==0.3.2
      - protobuf==6.31.1
      - psutil==7.0.0
      - pyarrow==21.0.0
      - pybind11==3.0.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pyparsing==3.3.1
      - pytablewriter==1.2.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.4
      - rouge-score==0.1.2
      - sacrebleu==2.5.1
      - safetensors==0.5.3
      - scikit-learn==1.7.1
      - scipy==1.16.0
      - sentencepiece==0.2.0
      - sentry-sdk==2.33.2
      - six==1.17.0
      - smmap==5.0.2
      - sqlitedict==2.1.0
      - sympy==1.14.0
      - tabledata==1.3.4
      - tabulate==0.9.0
      - tcolorpy==0.1.7
      - threadpoolctl==3.6.0
      - tokenizers==0.21.2
      - torch==2.7.1+cu128
      - torchaudio==2.7.1+cu128
      - torchvision==0.22.1+cu128
      - tqdm==4.67.1
      - tqdm-multiprocess==0.0.11
      - transformers==4.49.0
      - triton==3.3.1
      - typepy==1.3.4
      - typing-extensions==4.14.1
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - wandb==0.21.0
      - word2number==1.1
      - xxhash==3.5.0
      - yarl==1.20.1
      - zstandard==0.23.0
prefix: /orange/sgao1/sgao1/miniconda3/envs/llm-env
